### ISSUE TITLE
[BE][Feat] 커뮤니티 글 작성

### ISSUE THREAD

**Issue by Sniij** [codestates-seb/seb43_main_009#21]
: 로그인한 유저만 글 작성 페이지로 넘어올 수 있다.
: 제목과 내용을 빈 칸으로 POST 할 수 없다.

**Comment by ggggggggithub** [comment]
issue 작성하는 기계세요?

**Comment by Sniij** [comment]
> issue 작성하는 기계세요?

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ다시 수정해야 할 수도 있읍니다..ㅎㅎ
